### ISSUE TITLE
vite-node 0.25.5 prevents code from running, blocking test:playground

### ISSUE THREAD

**Issue by Tanimodori** [Tanimodori/viteburner#14]
The deployment build was successful and it will only affect testing while developing. I suggest to change the whole repo structure using pnpm workspace like `vite-plugin-dts`.

**Comment by Tanimodori** [comment]
Ok I found the smoking gun:

```bash
D:\Tanimodori\Project\__3RD__\@@bitburner\viteburner>set VITE_NODE_DEBUG_DUMP=true && npx vite-node ./src/utils.ts 
[vite-node] [debug] dump modules to D:/Tanimodori/Project/__3RD__/@@bitburner/viteburner/.vite-node/dump
D:\Tanimodori\Project\__3RD__\@@bitburner\viteburner\src\utils.ts:58
}}


SyntaxError: Unexpected end of input
    at new Script (node:vm:100:7)
    at createScript (node:vm:265:10)
    at Object.runInThisContext (node:vm:313:10)
    at ViteNodeRunner.directRequest (file:///D:/Tanimodori/Project/__3RD__/@@bitburner/viteburner/node_modules/vite-node/dist/client.mjs:307:19)
    at ViteNodeRunner.cachedRequest (file:///D:/Tanimodori/Project/__3RD__/@@bitburner/viteburner/node_modules/vite-node/dist/client.mjs:156:14)
    at ViteNodeRunner.executeFile (file:///D:/Tanimodori/Project/__3RD__/@@bitburner/viteburner/node_modules/vite-node/dist/client.mjs:133:12)
    at CAC.run (file:///D:/Tanimodori/Project/__3RD__/@@bitburner/viteburner/node_modules/vite-node/dist/cli.mjs:70:5)
```

Which is transforming from

```ts
import { SourceMap } from 'rollup';
import fs from 'fs';
import path from 'path';

export function getSourceMapString(map?: SourceMap | null): string {
  if (!map) return '';
  const mapDataString = JSON.stringify(map);
  return `//# sourceMappingURL=data:application/json;base64,${Buffer.from(mapDataString).toString('base64')}`;
}

export async function writeFile(file: string, content: string) {
  const dir = path.dirname(file);
  if (!fs.existsSync(dir)) {
    await fs.promises.mkdir(dir, { recursive: true });
  }
  return fs.promises.writeFile(file, content, {
    flag: 'w',
    encoding: 'utf8',
  });
}

export function isScriptFile(filename: string) {
  return filename.endsWith('.js') || filename.endsWith('.script');
}

/** Enforce starting slash */
export const forceStartingSlash = (s: string) => {
  return s.startsWith('/') ? s : '/' + s;
};

/** Enforce starting slash if file is not in root dir */
export const fixStartingSlash = (s: string) => {
  const index = s.lastIndexOf('/');
  if (index === 0) {
    // if file is in root dir with starting slash, remove it
    return s.substring(1);
  } else if (index !== -1) {
    // if file is not in root dir, add starting slash
    return forceStartingSlash(s);
  } else {
    // if file is in root dir without starting slash, keep it as-is
    return s;
  }
};

/** Remove starting slash on download */
export const removeStartingSlash = (s: string) => {
  return s.startsWith('/') ? s.substring(1) : s;
};

export const defaultUploadLocation = (file: string) => {
  return file.replace(/^src\//, '').replace(/\.ts$/, '.js');
};

// from vite packages\vite\src\node\utils.ts
export const externalRE = /^(https?:)?\/\//;
export const isExternalUrl = (url: string): boolean => externalRE.test(url);
```

to

```js
// D:/Tanimodori/Project/__3RD__/@@bitburner/viteburner/src/utils.ts
const __vite_ssr_import_0__ = await __vite_ssr_import__("fs");

const __vite_ssr_import_1__ = await __vite_ssr_import__("path");

function getSourceMapString(map) {
  if (!map)
    return "";
  const mapDataString = JSON.stringify(map);
  return `
}
Object.defineProperty(__vite_ssr_exports__, "getSourceMapString", { enumerable: true, configurable: true, get(){ return getSourceMapString }});
async function writeFile(file, content) {
  const dir = __vite_ssr_import_1__.default.dirname(file);
  if (!__vite_ssr_import_0__.default.existsSync(dir)) {
    await __vite_ssr_import_0__.default.promises.mkdir(dir, { recursive: true });
  }
  return __vite_ssr_import_0__.default.promises.writeFile(file, content, {
    flag: "w",
    encoding: "utf8"
  });
}
Object.defineProperty(__vite_ssr_exports__, "writeFile", { enumerable: true, configurable: true, get(){ return writeFile }});
function isScriptFile(filename) {
  return filename.endsWith(".js") || filename.endsWith(".script");
}
Object.defineProperty(__vite_ssr_exports__, "isScriptFile", { enumerable: true, configurable: true, get(){ return isScriptFile }});
const forceStartingSlash = (s) => {
  return s.startsWith("/") ? s : "/" + s;
};
Object.defineProperty(__vite_ssr_exports__, "forceStartingSlash", { enumerable: true, configurable: true, get(){ return forceStartingSlash }});
const fixStartingSlash = (s) => {
  const index = s.lastIndexOf("/");
  if (index === 0) {
    return s.substring(1);
  } else if (index !== -1) {
    return forceStartingSlash(s);
  } else {
    return s;
  }
};
Object.defineProperty(__vite_ssr_exports__, "fixStartingSlash", { enumerable: true, configurable: true, get(){ return fixStartingSlash }});
const removeStartingSlash = (s) => {
  return s.startsWith("/") ? s.substring(1) : s;
};
Object.defineProperty(__vite_ssr_exports__, "removeStartingSlash", { enumerable: true, configurable: true, get(){ return removeStartingSlash }});
const defaultUploadLocation = (file) => {
  return file.replace(/^src\//, "").replace(/\.ts$/, ".js");
};
Object.defineProperty(__vite_ssr_exports__, "defaultUploadLocation", { enumerable: true, configurable: true, get(){ return defaultUploadLocation }});
const externalRE = /^(https?:)?\/\//;
Object.defineProperty(__vite_ssr_exports__, "externalRE", { enumerable: true, configurable: true, get(){ return externalRE }});
const isExternalUrl = (url) => externalRE.test(url);
Object.defineProperty(__vite_ssr_exports__, "isExternalUrl", { enumerable: true, configurable: true, get(){ return isExternalUrl }});

//# sourceMappingSource=vite-node
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6IjtBQUNlOztBQUNFO0FBRVYsU0FBUyxtQkFBbUIsS0FBZ0M7QUFDakUsTUFBSSxDQUFDO0FBQUssV0FBTztBQUNqQixRQUFNLGdCQUFnQixLQUFLLFVBQVUsR0FBRztBQUN4QyxTQUFPLHFEQUFxRCxPQUFPLEtBQUssYUFBYSxFQUFFLFNBQVMsUUFBUTtBQUMxRzsrSUFBQTtBQUVBLGVBQXNCLFVBQVUsTUFBYyxTQUFpQjtBQUM3RCxRQUFNLE1BQU0sOEJBQUssUUFBUSxJQUFJO0FBQzdCLE1BQUksQ0FBQyw4QkFBRyxXQUFXLEdBQUcsR0FBRztBQUN2QixVQUFNLDhCQUFHLFNBQVMsTUFBTSxLQUFLLEVBQUUsV0FBVyxLQUFLLENBQUM7QUFBQSxFQUNsRDtBQUNBLFNBQU8sOEJBQUcsU0FBUyxVQUFVLE1BQU0sU0FBUztBQUFBLElBQzFDLE1BQU07QUFBQSxJQUNOLFVBQVU7QUFBQSxFQUNaLENBQUM7QUFDSDs2SEFBQTtBQUVPLFNBQVMsYUFBYSxVQUFrQjtBQUM3QyxTQUFPLFNBQVMsU0FBUyxLQUFLLEtBQUssU0FBUyxTQUFTLFNBQVM7QUFDaEU7bUlBQUE7QUFHTyxNQUFNLHFCQUFxQixDQUFDLE1BQWM7QUFDL0MsU0FBTyxFQUFFLFdBQVcsR0FBRyxJQUFJLElBQUksTUFBTTtBQUN2QzsrSUFBQTtBQUdPLE1BQU0sbUJBQW1CLENBQUMsTUFBYztBQUM3QyxRQUFNLFFBQVEsRUFBRSxZQUFZLEdBQUc7QUFDL0IsTUFBSSxVQUFVLEdBQUc7QUFFZixXQUFPLEVBQUUsVUFBVSxDQUFDO0FBQUEsRUFDdEIsV0FBVyxVQUFVLElBQUk7QUFFdkIsV0FBTyxtQkFBbUIsQ0FBQztBQUFBLEVBQzdCLE9BQU87QUFFTCxXQUFPO0FBQUEsRUFDVDtBQUNGOzJJQUFBO0FBR08sTUFBTSxzQkFBc0IsQ0FBQyxNQUFjO0FBQ2hELFNBQU8sRUFBRSxXQUFXLEdBQUcsSUFBSSxFQUFFLFVBQVUsQ0FBQyxJQUFJO0FBQzlDO2lKQUFBO0FBRU8sTUFBTSx3QkFBd0IsQ0FBQyxTQUFpQjtBQUNyRCxTQUFPLEtBQUssUUFBUSxVQUFVLEVBQUUsRUFBRSxRQUFRLFNBQVMsS0FBSztBQUMxRDtxSkFBQTtBQUdPLE1BQU0sYUFBYTsrSEFBQTtBQUNuQixNQUFNLGdCQUFnQixDQUFDLFFBQXlCLFdBQVcsS0FBSyxHQUFHO3FJQUFBIiwibmFtZXMiOltdLCJzb3VyY2VzIjpbIkQ6L1Rhbmltb2RvcmkvUHJvamVjdC9fXzNSRF9fL0BAYml0YnVybmVyL3ZpdGVidXJuZXIvc3JjL3V0aWxzLnRzIl0sInNvdXJjZXNDb250ZW50IjpbImltcG9ydCB7IFNvdXJjZU1hcCB9IGZyb20gJ3JvbGx1cCc7XHJcbmltcG9ydCBmcyBmcm9tICdmcyc7XHJcbmltcG9ydCBwYXRoIGZyb20gJ3BhdGgnO1xyXG5cclxuZXhwb3J0IGZ1bmN0aW9uIGdldFNvdXJjZU1hcFN0cmluZyhtYXA/OiBTb3VyY2VNYXAgfCBudWxsKTogc3RyaW5nIHtcclxuICBpZiAoIW1hcCkgcmV0dXJuICcnO1xyXG4gIGNvbnN0IG1hcERhdGFTdHJpbmcgPSBKU09OLnN0cmluZ2lmeShtYXApO1xyXG4gIHJldHVybiBgLy8jIHNvdXJjZU1hcHBpbmdVUkw9ZGF0YTphcHBsaWNhdGlvbi9qc29uO2Jhc2U2NCwke0J1ZmZlci5mcm9tKG1hcERhdGFTdHJpbmcpLnRvU3RyaW5nKCdiYXNlNjQnKX1gO1xyXG59XHJcblxyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gd3JpdGVGaWxlKGZpbGU6IHN0cmluZywgY29udGVudDogc3RyaW5nKSB7XHJcbiAgY29uc3QgZGlyID0gcGF0aC5kaXJuYW1lKGZpbGUpO1xyXG4gIGlmICghZnMuZXhpc3RzU3luYyhkaXIpKSB7XHJcbiAgICBhd2FpdCBmcy5wcm9taXNlcy5ta2RpcihkaXIsIHsgcmVjdXJzaXZlOiB0cnVlIH0pO1xyXG4gIH1cclxuICByZXR1cm4gZnMucHJvbWlzZXMud3JpdGVGaWxlKGZpbGUsIGNvbnRlbnQsIHtcclxuICAgIGZsYWc6ICd3JyxcclxuICAgIGVuY29kaW5nOiAndXRmOCcsXHJcbiAgfSk7XHJcbn1cclxuXHJcbmV4cG9ydCBmdW5jdGlvbiBpc1NjcmlwdEZpbGUoZmlsZW5hbWU6IHN0cmluZykge1xyXG4gIHJldHVybiBmaWxlbmFtZS5lbmRzV2l0aCgnLmpzJykgfHwgZmlsZW5hbWUuZW5kc1dpdGgoJy5zY3JpcHQnKTtcclxufVxyXG5cclxuLyoqIEVuZm9yY2Ugc3RhcnRpbmcgc2xhc2ggKi9cclxuZXhwb3J0IGNvbnN0IGZvcmNlU3RhcnRpbmdTbGFzaCA9IChzOiBzdHJpbmcpID0+IHtcclxuICByZXR1cm4gcy5zdGFydHNXaXRoKCcvJykgPyBzIDogJy8nICsgcztcclxufTtcclxuXHJcbi8qKiBFbmZvcmNlIHN0YXJ0aW5nIHNsYXNoIGlmIGZpbGUgaXMgbm90IGluIHJvb3QgZGlyICovXHJcbmV4cG9ydCBjb25zdCBmaXhTdGFydGluZ1NsYXNoID0gKHM6IHN0cmluZykgPT4ge1xyXG4gIGNvbnN0IGluZGV4ID0gcy5sYXN0SW5kZXhPZignLycpO1xyXG4gIGlmIChpbmRleCA9PT0gMCkge1xyXG4gICAgLy8gaWYgZmlsZSBpcyBpbiByb290IGRpciB3aXRoIHN0YXJ0aW5nIHNsYXNoLCByZW1vdmUgaXRcclxuICAgIHJldHVybiBzLnN1YnN0cmluZygxKTtcclxuICB9IGVsc2UgaWYgKGluZGV4ICE9PSAtMSkge1xyXG4gICAgLy8gaWYgZmlsZSBpcyBub3QgaW4gcm9vdCBkaXIsIGFkZCBzdGFydGluZyBzbGFzaFxyXG4gICAgcmV0dXJuIGZvcmNlU3RhcnRpbmdTbGFzaChzKTtcclxuICB9IGVsc2Uge1xyXG4gICAgLy8gaWYgZmlsZSBpcyBpbiByb290IGRpciB3aXRob3V0IHN0YXJ0aW5nIHNsYXNoLCBrZWVwIGl0IGFzLWlzXHJcbiAgICByZXR1cm4gcztcclxuICB9XHJcbn07XHJcblxyXG4vKiogUmVtb3ZlIHN0YXJ0aW5nIHNsYXNoIG9uIGRvd25sb2FkICovXHJcbmV4cG9ydCBjb25zdCByZW1vdmVTdGFydGluZ1NsYXNoID0gKHM6IHN0cmluZykgPT4ge1xyXG4gIHJldHVybiBzLnN0YXJ0c1dpdGgoJy8nKSA/IHMuc3Vic3RyaW5nKDEpIDogcztcclxufTtcclxuXHJcbmV4cG9ydCBjb25zdCBkZWZhdWx0VXBsb2FkTG9jYXRpb24gPSAoZmlsZTogc3RyaW5nKSA9PiB7XHJcbiAgcmV0dXJuIGZpbGUucmVwbGFjZSgvXnNyY1xcLy8sICcnKS5yZXBsYWNlKC9cXC50cyQvLCAnLmpzJyk7XHJcbn07XHJcblxyXG4vLyBmcm9tIHZpdGUgcGFja2FnZXNcXHZpdGVcXHNyY1xcbm9kZVxcdXRpbHMudHNcclxuZXhwb3J0IGNvbnN0IGV4dGVybmFsUkUgPSAvXihodHRwcz86KT9cXC9cXC8vO1xyXG5leHBvcnQgY29uc3QgaXNFeHRlcm5hbFVybCA9ICh1cmw6IHN0cmluZyk6IGJvb2xlYW4gPT4gZXh0ZXJuYWxSRS50ZXN0KHVybCk7XHJcbiJdLCJmaWxlIjoiRDovVGFuaW1vZG9yaS9Qcm9qZWN0L19fM1JEX18vQEBiaXRidXJuZXIvdml0ZWJ1cm5lci9zcmMvdXRpbHMudHMifQ==
```

So there's a missing backtick here.

**Comment by Tanimodori** [comment]
Upstream issue https://github.com/vitest-dev/vitest/issues/2918
